//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfChurgel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dishes
    {
        public Dishes()
        {
            this.DishOrderRelation = new HashSet<DishOrderRelation>();
            this.ProductDishRelation = new HashSet<ProductDishRelation>();
            this.Menu = new HashSet<Menu>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdTypeDishes { get; set; }
    
        public virtual ICollection<DishOrderRelation> DishOrderRelation { get; set; }
        public virtual TypeDishes TypeDishes { get; set; }
        public virtual ICollection<ProductDishRelation> ProductDishRelation { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
    }
}
