//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfChurgel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Dishes = new HashSet<Dishes>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ICollection<Dishes> Dishes { get; set; }
    }
}
