//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfChurgel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeDishes
    {
        public TypeDishes()
        {
            this.Dishes = new HashSet<Dishes>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Dishes> Dishes { get; set; }
    }
}
